# Generated by Django 5.2.4 on 2025-08-06 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_submission_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="submission",
            table="submission",
        ),
    ]
