# 이 파일은 generate_config.py에 의해 자동으로 생성되었습니다.
# 직접 수정하지 마세요.

UNIVERSITY_DATA = {   '건국대': {   '2023': {   '문항1': {   'id': 'konkuk_2023_1',
                                      'pages': [   'pdf_pages/konkuk_2023_1/page_1.png',
                                                   'pdf_pages/konkuk_2023_1/page_2.png',
                                                   'pdf_pages/konkuk_2023_1/page_3.png']}},
               '2024': {   '문항1': {   'id': 'konkuk_2024_1',
                                      'pages': [   'pdf_pages/konkuk_2024_1/page_1.png',
                                                   'pdf_pages/konkuk_2024_1/page_2.png',
                                                   'pdf_pages/konkuk_2024_1/page_3.png',
                                                   'pdf_pages/konkuk_2024_1/page_4.png']}}},
    '경희대': {   '2023': {   '문항1': {   'id': 'khu_2023_1',
                                      'pages': [   'pdf_pages/khu_2023_1/page_1.png',
                                                   'pdf_pages/khu_2023_1/page_2.png',
                                                   'pdf_pages/khu_2023_1/page_3.png',
                                                   'pdf_pages/khu_2023_1/page_4.png']}},
               '2024': {   '문항1': {   'id': 'khu_2024_1',
                                      'pages': [   'pdf_pages/khu_2024_1/page_1.png',
                                                   'pdf_pages/khu_2024_1/page_2.png',
                                                   'pdf_pages/khu_2024_1/page_3.png',
                                                   'pdf_pages/khu_2024_1/page_4.png']}}},
    '동국대': {   '2023': {   '문항1': {   'id': 'dongguk_2023_1',
                                      'pages': [   'pdf_pages/dongguk_2023_1/page_1.png',
                                                   'pdf_pages/dongguk_2023_1/page_2.png',
                                                   'pdf_pages/dongguk_2023_1/page_3.png',
                                                   'pdf_pages/dongguk_2023_1/page_4.png',
                                                   'pdf_pages/dongguk_2023_1/page_5.png',
                                                   'pdf_pages/dongguk_2023_1/page_6.png',
                                                   'pdf_pages/dongguk_2023_1/page_7.png']}},
               '2024': {   '문항1': {   'id': 'dongguk_2024_1',
                                      'pages': [   'pdf_pages/dongguk_2024_1/page_1.png',
                                                   'pdf_pages/dongguk_2024_1/page_2.png',
                                                   'pdf_pages/dongguk_2024_1/page_3.png',
                                                   'pdf_pages/dongguk_2024_1/page_4.png',
                                                   'pdf_pages/dongguk_2024_1/page_5.png',
                                                   'pdf_pages/dongguk_2024_1/page_6.png',
                                                   'pdf_pages/dongguk_2024_1/page_7.png',
                                                   'pdf_pages/dongguk_2024_1/page_8.png']}}},
    '서강대': {   '2023': {   '문항1': {   'id': 'sogang_2023_1',
                                      'pages': [   'pdf_pages/sogang_2023_1/page_1.png',
                                                   'pdf_pages/sogang_2023_1/page_2.png']},
                           '문항2': {   'id': 'sogang_2023_2',
                                      'pages': [   'pdf_pages/sogang_2023_2/page_1.png',
                                                   'pdf_pages/sogang_2023_2/page_2.png']},
                           '문항3': {   'id': 'sogang_2023_3',
                                      'pages': [   'pdf_pages/sogang_2023_3/page_1.png',
                                                   'pdf_pages/sogang_2023_3/page_2.png']},
                           '문항4': {   'id': 'sogang_2023_4',
                                      'pages': [   'pdf_pages/sogang_2023_4/page_1.png',
                                                   'pdf_pages/sogang_2023_4/page_2.png']}},
               '2024': {   '문항1': {   'id': 'sogang_2024_1',
                                      'pages': [   'pdf_pages/sogang_2024_1/page_1.png',
                                                   'pdf_pages/sogang_2024_1/page_2.png',
                                                   'pdf_pages/sogang_2024_1/page_3.png']},
                           '문항2': {   'id': 'sogang_2024_2',
                                      'pages': [   'pdf_pages/sogang_2024_2/page_1.png',
                                                   'pdf_pages/sogang_2024_2/page_2.png']},
                           '문항3': {   'id': 'sogang_2024_3',
                                      'pages': [   'pdf_pages/sogang_2024_3/page_1.png',
                                                   'pdf_pages/sogang_2024_3/page_2.png']}}},
    '성균관대': {   '2023': {   '문항1': {   'id': 'skku_2023_1',
                                       'pages': [   'pdf_pages/skku_2023_1/page_1.png',
                                                    'pdf_pages/skku_2023_1/page_2.png',
                                                    'pdf_pages/skku_2023_1/page_3.png',
                                                    'pdf_pages/skku_2023_1/page_4.png',
                                                    'pdf_pages/skku_2023_1/page_5.png']},
                            '문항2': {   'id': 'skku_2023_2',
                                       'pages': [   'pdf_pages/skku_2023_2/page_1.png',
                                                    'pdf_pages/skku_2023_2/page_2.png',
                                                    'pdf_pages/skku_2023_2/page_3.png',
                                                    'pdf_pages/skku_2023_2/page_4.png',
                                                    'pdf_pages/skku_2023_2/page_5.png']}}},
    '숙명여대': {   '2023': {   '문항1': {   'id': 'sookmyung_2023_1',
                                       'pages': [   'pdf_pages/sookmyung_2023_1/page_1.png',
                                                    'pdf_pages/sookmyung_2023_1/page_2.png',
                                                    'pdf_pages/sookmyung_2023_1/page_3.png',
                                                    'pdf_pages/sookmyung_2023_1/page_4.png']},
                            '문항2': {   'id': 'sookmyung_2023_2',
                                       'pages': [   'pdf_pages/sookmyung_2023_2/page_1.png',
                                                    'pdf_pages/sookmyung_2023_2/page_2.png',
                                                    'pdf_pages/sookmyung_2023_2/page_3.png',
                                                    'pdf_pages/sookmyung_2023_2/page_4.png']}}},
    '숭실대': {   '2023': {   '문항1': {   'id': 'soongsil_2023_1',
                                      'pages': [   'pdf_pages/soongsil_2023_1/page_1.png',
                                                   'pdf_pages/soongsil_2023_1/page_2.png',
                                                   'pdf_pages/soongsil_2023_1/page_3.png']}},
               '2024': {   '문항1': {   'id': 'soongsil_2024_1',
                                      'pages': [   'pdf_pages/soongsil_2024_1/page_1.png',
                                                   'pdf_pages/soongsil_2024_1/page_2.png',
                                                   'pdf_pages/soongsil_2024_1/page_3.png',
                                                   'pdf_pages/soongsil_2024_1/page_4.png']}}},
    '아주대': {   '2023': {   '문항1': {   'id': 'ajou_2023_1',
                                      'pages': [   'pdf_pages/ajou_2023_1/page_1.png',
                                                   'pdf_pages/ajou_2023_1/page_2.png',
                                                   'pdf_pages/ajou_2023_1/page_3.png',
                                                   'pdf_pages/ajou_2023_1/page_4.png',
                                                   'pdf_pages/ajou_2023_1/page_5.png']}},
               '2024': {   '문항1': {   'id': 'ajou_2024_1',
                                      'pages': [   'pdf_pages/ajou_2024_1/page_1.png',
                                                   'pdf_pages/ajou_2024_1/page_2.png',
                                                   'pdf_pages/ajou_2024_1/page_3.png',
                                                   'pdf_pages/ajou_2024_1/page_4.png',
                                                   'pdf_pages/ajou_2024_1/page_5.png']}}},
    '이화여대': {   '2024': {   '문항1': {   'id': 'ewha_2024_1',
                                       'pages': [   'pdf_pages/ewha_2024_1/page_1.png',
                                                    'pdf_pages/ewha_2024_1/page_2.png',
                                                    'pdf_pages/ewha_2024_1/page_3.png']}}},
    '한국외대': {   '2024': {   '문항1': {   'id': 'hufs_2024_1',
                                       'pages': [   'pdf_pages/hufs_2024_1/page_1.png',
                                                    'pdf_pages/hufs_2024_1/page_2.png',
                                                    'pdf_pages/hufs_2024_1/page_3.png']},
                            '문항2': {   'id': 'hufs_2024_2',
                                       'pages': [   'pdf_pages/hufs_2024_2/page_1.png',
                                                    'pdf_pages/hufs_2024_2/page_2.png',
                                                    'pdf_pages/hufs_2024_2/page_3.png',
                                                    'pdf_pages/hufs_2024_2/page_4.png']}}},
    '홍익대': {   '2023': {   '문항1': {   'id': 'hongik_2023_1',
                                      'pages': [   'pdf_pages/hongik_2023_1/page_1.png',
                                                   'pdf_pages/hongik_2023_1/page_2.png',
                                                   'pdf_pages/hongik_2023_1/page_3.png']},
                           '문항2': {   'id': 'hongik_2023_2',
                                      'pages': [   'pdf_pages/hongik_2023_2/page_1.png',
                                                   'pdf_pages/hongik_2023_2/page_2.png',
                                                   'pdf_pages/hongik_2023_2/page_3.png']},
                           '문항3': {   'id': 'hongik_2023_3',
                                      'pages': [   'pdf_pages/hongik_2023_3/page_1.png',
                                                   'pdf_pages/hongik_2023_3/page_2.png',
                                                   'pdf_pages/hongik_2023_3/page_3.png']},
                           '문항4': {   'id': 'hongik_2023_4',
                                      'pages': [   'pdf_pages/hongik_2023_4/page_1.png',
                                                   'pdf_pages/hongik_2023_4/page_2.png']}},
               '2024': {   '문항1': {   'id': 'hongik_2024_1',
                                      'pages': [   'pdf_pages/hongik_2024_1/page_1.png',
                                                   'pdf_pages/hongik_2024_1/page_2.png',
                                                   'pdf_pages/hongik_2024_1/page_3.png']},
                           '문항2': {   'id': 'hongik_2024_2',
                                      'pages': [   'pdf_pages/hongik_2024_2/page_1.png',
                                                   'pdf_pages/hongik_2024_2/page_2.png',
                                                   'pdf_pages/hongik_2024_2/page_3.png']},
                           '문항3': {   'id': 'hongik_2024_3',
                                      'pages': [   'pdf_pages/hongik_2024_3/page_1.png',
                                                   'pdf_pages/hongik_2024_3/page_2.png',
                                                   'pdf_pages/hongik_2024_3/page_3.png']},
                           '문항4': {   'id': 'hongik_2024_4',
                                      'pages': [   'pdf_pages/hongik_2024_4/page_1.png',
                                                   'pdf_pages/hongik_2024_4/page_2.png',
                                                   'pdf_pages/hongik_2024_4/page_3.png']}}}}
